server:
  port: 8080

bfhl:
  base-url: "https://bfhldevapigw.healthrx.co.in/hiring"
  language: "JAVA"

candidate:
  name: "Amandeep Singh Khalsa"        
  reg-no: "22BCE11061"     
  email: "amandeepsinghkhalsa2022@vitbhopal.ac.in" 
